apiVersion: v1
kind: Service
metadata:
  name: society-festival-committee-service
spec:
  selector:
    app: society-festival-committee-service
  ports:
    - port: 80
      targetPort: 9096
  type: ClusterIP
